---
# 1) Validate first
- name: Validate nginx configuration
  listen: validate and reload nginx
  ansible.builtin.command: nginx -t
  register: nginx_check
  changed_when: false
  failed_when: nginx_check.rc != 0

# 2) Only reload if validation passed
- name: Reload nginx
  listen: validate and reload nginx
  ansible.builtin.service:
    name: "{{ nginx_service }}"
    state: reloaded
#dsfd